### PR TITLE
Update kingdom.pwn

### PR DESCRIPTION
**Pull request by Bronzal**
Tab vs space

### CODE REVIEW

**Comment by Bronzal** [comment]
You're right, It's pretty much useless commit and it's has nothing to do with history.

**Comment by Bronzal** [comment]
image
I mean... Still nothing but something right?

**Comment by chromaerror** [comment]
Yes I can see that you removed a few tabs and changed to spaces or something but whats the benefit except for getting 1 more commit? the code isn't any more clear than it used to be, nor does it affect anything.

**Comment by Bronzal** [comment]
S T Y L 1 N G

**Comment by chromaerror** [comment]
Completely irrelevant then. I don't recommend merging this, but it's not up to me.

**Comment by Bronzal** [comment]
It's not a big problem if they don't merge it. As you said and as I confirm, in this PR - nothing is important.

**Pull request closed without merging**
